services:
  fastapi:
    build:
      args:
        INSTALL_TEST_DEPENDENCIES: 1
    ports:
      - "5500:5500"
    command: ["python", "run_local.py"]
    env_file:
      - "env/local.env"
    volumes:
      - .:/app
    depends_on:
      - dynamodb-local
  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal